### ISSUE TITLE
Make Home Page Title and Icon and Logo Replaceable.

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#38] opened 2021-10-23 09:26 UTC
(C24 and C25) Make the home page title and the icon and logo image replaceable by the administrator.

**Comment by audrius-a** [comment] 2023-04-30 19:32
My suggestion is to have a Maintenance/Preferences option where we can configure Title and upload the logo. The title would be stored in the database while the logo would be stored alongside the database in `C:\ProgramData\Talking Newspapers\TNBase` folder.

**Comment by achrisdale** [comment] 2023-04-30 20:23
OK. We can do that, but I think changing the title needs to be an 
administrator only privilege when we have an administrator log-in 
password. I can see that stopping anyone from changing the logo and the 
icon would be difficult.

Chris

In message ***@***.***>

**Comment by audrius-a** [comment] 2023-04-30 20:31
If you want to prevent logo change by an unauthorized user, i.e. manually copy the image to the Program Data folder when we can certainly put the image into the database itself. I believe that's an easy thing to do but I didn't see it to be necessary. Of course, once the user login is implemented, the menu option to change the title and logo would be visible to administrators only.

**Comment by achrisdale** [comment] 2023-04-30 20:55
It's unlikely that a user would try to change the logo unless authorised.
Good that menu option to change the title and logo would be visible to 
administrators only.

Chris


In message ***@***.***>

**Comment by audrius-a** [comment] 2024-05-06 10:35
Closing as this is a duplicate of #110 which is now closed

**Closed as completed by audrius-a** 2024-05-06 10:35 UTC
